// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _lilylcm_04Dan_h
#define _lilylcm_04Dan_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _lilylcm_04Dan lilylcm_04Dan;
struct _lilylcm_04Dan
{
    char*      name;
};

/**
 * Create a deep copy of a lilylcm_04Dan.
 * When no longer needed, destroy it with lilylcm_04Dan_destroy()
 */
lilylcm_04Dan* lilylcm_04Dan_copy(const lilylcm_04Dan* to_copy);

/**
 * Destroy an instance of lilylcm_04Dan created by lilylcm_04Dan_copy()
 */
void lilylcm_04Dan_destroy(lilylcm_04Dan* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _lilylcm_04Dan_subscription_t lilylcm_04Dan_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * lilylcm_04Dan is received.
 */
typedef void(*lilylcm_04Dan_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const lilylcm_04Dan *msg, void *userdata);

/**
 * Publish a message of type lilylcm_04Dan using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int lilylcm_04Dan_publish(lcm_t *lcm, const char *channel, const lilylcm_04Dan *msg);

/**
 * Subscribe to messages of type lilylcm_04Dan using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is received.
 *                This function is invoked by LCM during calls to lcm_handle() and
 *                lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
lilylcm_04Dan_subscription_t* lilylcm_04Dan_subscribe(lcm_t *lcm, const char *channel, lilylcm_04Dan_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by lilylcm_04Dan_subscribe()
 */
int lilylcm_04Dan_unsubscribe(lcm_t *lcm, lilylcm_04Dan_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int lilylcm_04Dan_subscription_set_queue_capacity(lilylcm_04Dan_subscription_t* subs,
                              int num_messages);

/**
 * Encode a message of type lilylcm_04Dan into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to lilylcm_04Dan_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int lilylcm_04Dan_encode(void *buf, int offset, int maxlen, const lilylcm_04Dan *p);

/**
 * Decode a message of type lilylcm_04Dan from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with lilylcm_04Dan_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int lilylcm_04Dan_decode(const void *buf, int offset, int maxlen, lilylcm_04Dan *msg);

/**
 * Release resources allocated by lilylcm_04Dan_decode()
 * @return 0
 */
int lilylcm_04Dan_decode_cleanup(lilylcm_04Dan *p);

/**
 * Check how many bytes are required to encode a message of type lilylcm_04Dan
 */
int lilylcm_04Dan_encoded_size(const lilylcm_04Dan *p);

// LCM support functions. Users should not call these
int64_t __lilylcm_04Dan_get_hash(void);
int64_t __lilylcm_04Dan_hash_recursive(const __lcm_hash_ptr *p);
int     __lilylcm_04Dan_encode_array(void *buf, int offset, int maxlen, const lilylcm_04Dan *p, int elements);
int     __lilylcm_04Dan_decode_array(const void *buf, int offset, int maxlen, lilylcm_04Dan *p, int elements);
int     __lilylcm_04Dan_decode_array_cleanup(lilylcm_04Dan *p, int elements);
int     __lilylcm_04Dan_encoded_array_size(const lilylcm_04Dan *p, int elements);
int     __lilylcm_04Dan_clone_array(const lilylcm_04Dan *p, lilylcm_04Dan *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
