// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "lilylcm_04Dan.h"

static int __lilylcm_04Dan_hash_computed;
static int64_t __lilylcm_04Dan_hash;

int64_t __lilylcm_04Dan_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __lilylcm_04Dan_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__lilylcm_04Dan_get_hash;
    (void) cp;

    int64_t hash = (int64_t)0x90df9b84b9cebd12LL
         + __string_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __lilylcm_04Dan_get_hash(void)
{
    if (!__lilylcm_04Dan_hash_computed) {
        __lilylcm_04Dan_hash = __lilylcm_04Dan_hash_recursive(NULL);
        __lilylcm_04Dan_hash_computed = 1;
    }

    return __lilylcm_04Dan_hash;
}

int __lilylcm_04Dan_encode_array(void *buf, int offset, int maxlen, const lilylcm_04Dan *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].name), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int lilylcm_04Dan_encode(void *buf, int offset, int maxlen, const lilylcm_04Dan *p)
{
    int pos = 0, thislen;
    int64_t hash = __lilylcm_04Dan_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __lilylcm_04Dan_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __lilylcm_04Dan_encoded_array_size(const lilylcm_04Dan *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __string_encoded_array_size(&(p[element].name), 1);

    }
    return size;
}

int lilylcm_04Dan_encoded_size(const lilylcm_04Dan *p)
{
    return 8 + __lilylcm_04Dan_encoded_array_size(p, 1);
}

int __lilylcm_04Dan_decode_array(const void *buf, int offset, int maxlen, lilylcm_04Dan *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].name), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __lilylcm_04Dan_decode_array_cleanup(lilylcm_04Dan *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __string_decode_array_cleanup(&(p[element].name), 1);

    }
    return 0;
}

int lilylcm_04Dan_decode(const void *buf, int offset, int maxlen, lilylcm_04Dan *p)
{
    int pos = 0, thislen;
    int64_t hash = __lilylcm_04Dan_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __lilylcm_04Dan_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int lilylcm_04Dan_decode_cleanup(lilylcm_04Dan *p)
{
    return __lilylcm_04Dan_decode_array_cleanup(p, 1);
}

int __lilylcm_04Dan_clone_array(const lilylcm_04Dan *p, lilylcm_04Dan *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __string_clone_array(&(p[element].name), &(q[element].name), 1);

    }
    return 0;
}

lilylcm_04Dan *lilylcm_04Dan_copy(const lilylcm_04Dan *p)
{
    lilylcm_04Dan *q = (lilylcm_04Dan*) malloc(sizeof(lilylcm_04Dan));
    __lilylcm_04Dan_clone_array(p, q, 1);
    return q;
}

void lilylcm_04Dan_destroy(lilylcm_04Dan *p)
{
    __lilylcm_04Dan_decode_array_cleanup(p, 1);
    free(p);
}

int lilylcm_04Dan_publish(lcm_t *lc, const char *channel, const lilylcm_04Dan *p)
{
      int max_data_size = lilylcm_04Dan_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = lilylcm_04Dan_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _lilylcm_04Dan_subscription_t {
    lilylcm_04Dan_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void lilylcm_04Dan_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    lilylcm_04Dan p;
    memset(&p, 0, sizeof(lilylcm_04Dan));
    status = lilylcm_04Dan_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding lilylcm_04Dan!!!\n", status);
        return;
    }

    lilylcm_04Dan_subscription_t *h = (lilylcm_04Dan_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    lilylcm_04Dan_decode_cleanup (&p);
}

lilylcm_04Dan_subscription_t* lilylcm_04Dan_subscribe (lcm_t *lcm,
                    const char *channel,
                    lilylcm_04Dan_handler_t f, void *userdata)
{
    lilylcm_04Dan_subscription_t *n = (lilylcm_04Dan_subscription_t*)
                       malloc(sizeof(lilylcm_04Dan_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 lilylcm_04Dan_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg lilylcm_04Dan LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int lilylcm_04Dan_subscription_set_queue_capacity (lilylcm_04Dan_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int lilylcm_04Dan_unsubscribe(lcm_t *lcm, lilylcm_04Dan_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe lilylcm_04Dan_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

