"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class L02Banana(object):
    __slots__ = ["done"]

    def __init__(self):
        self.done = False

    def encode(self):
        buf = BytesIO()
        buf.write(L02Banana._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.done))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != L02Banana._get_packed_fingerprint():
            raise ValueError("Decode error")
        return L02Banana._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = L02Banana()
        self.done = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if L02Banana in parents: return 0
        tmphash = (0xf5f7835443e7f1f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if L02Banana._packed_fingerprint is None:
            L02Banana._packed_fingerprint = struct.pack(">Q", L02Banana._get_hash_recursive([]))
        return L02Banana._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

