"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ebola(object):
    __slots__ = ["cured"]

    def __init__(self):
        self.cured = False

    def encode(self):
        buf = BytesIO()
        buf.write(ebola._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.cured))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ebola._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ebola._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ebola()
        self.cured = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ebola in parents: return 0
        tmphash = (0xad85c9a8b574d497) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ebola._packed_fingerprint is None:
            ebola._packed_fingerprint = struct.pack(">Q", ebola._get_hash_recursive([]))
        return ebola._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

