"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class L01Apple(object):
    __slots__ = ["count"]

    def __init__(self):
        self.count = 0

    def encode(self):
        buf = BytesIO()
        buf.write(L01Apple._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.count))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != L01Apple._get_packed_fingerprint():
            raise ValueError("Decode error")
        return L01Apple._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = L01Apple()
        self.count = struct.unpack(">b", buf.read(1))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if L01Apple in parents: return 0
        tmphash = (0x4ca686c4e8b59946) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if L01Apple._packed_fingerprint is None:
            L01Apple._packed_fingerprint = struct.pack(">Q", L01Apple._get_hash_recursive([]))
        return L01Apple._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

