"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class L06Depth(object):
    __slots__ = ["depth"]

    def __init__(self):
        self.depth = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(L06Depth._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">f", self.depth))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != L06Depth._get_packed_fingerprint():
            raise ValueError("Decode error")
        return L06Depth._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = L06Depth()
        self.depth = struct.unpack(">f", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if L06Depth in parents: return 0
        tmphash = (0x2f4da988c7d3aa31) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if L06Depth._packed_fingerprint is None:
            L06Depth._packed_fingerprint = struct.pack(">Q", L06Depth._get_hash_recursive([]))
        return L06Depth._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

