"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class L10ChargerRead(object):
    __slots__ = ["state", "charging"]

    def __init__(self):
        self.state = ""
        self.charging = False

    def encode(self):
        buf = BytesIO()
        buf.write(L10ChargerRead._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __state_encoded = self.state.encode('utf-8')
        buf.write(struct.pack('>I', len(__state_encoded)+1))
        buf.write(__state_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">b", self.charging))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != L10ChargerRead._get_packed_fingerprint():
            raise ValueError("Decode error")
        return L10ChargerRead._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = L10ChargerRead()
        __state_len = struct.unpack('>I', buf.read(4))[0]
        self.state = buf.read(__state_len)[:-1].decode('utf-8', 'replace')
        self.charging = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if L10ChargerRead in parents: return 0
        tmphash = (0x6c6864000ae7c182) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if L10ChargerRead._packed_fingerprint is None:
            L10ChargerRead._packed_fingerprint = struct.pack(">Q", L10ChargerRead._get_hash_recursive([]))
        return L10ChargerRead._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

