"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class L11GPS(object):
    __slots__ = ["longitude", "latitude"]

    def __init__(self):
        self.longitude = 0.0
        self.latitude = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(L11GPS._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ff", self.longitude, self.latitude))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != L11GPS._get_packed_fingerprint():
            raise ValueError("Decode error")
        return L11GPS._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = L11GPS()
        self.longitude, self.latitude = struct.unpack(">ff", buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if L11GPS in parents: return 0
        tmphash = (0x5f6daf6e1afb9084) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if L11GPS._packed_fingerprint is None:
            L11GPS._packed_fingerprint = struct.pack(">Q", L11GPS._get_hash_recursive([]))
        return L11GPS._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

