"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class L12XbeeRead(object):
    __slots__ = ["readin"]

    def __init__(self):
        self.readin = ""

    def encode(self):
        buf = BytesIO()
        buf.write(L12XbeeRead._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __readin_encoded = self.readin.encode('utf-8')
        buf.write(struct.pack('>I', len(__readin_encoded)+1))
        buf.write(__readin_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != L12XbeeRead._get_packed_fingerprint():
            raise ValueError("Decode error")
        return L12XbeeRead._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = L12XbeeRead()
        __readin_len = struct.unpack('>I', buf.read(4))[0]
        self.readin = buf.read(__readin_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if L12XbeeRead in parents: return 0
        tmphash = (0xf680593d2c803dca) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if L12XbeeRead._packed_fingerprint is None:
            L12XbeeRead._packed_fingerprint = struct.pack(">Q", L12XbeeRead._get_hash_recursive([]))
        return L12XbeeRead._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

