"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class L10ChargerComplete(object):
    __slots__ = ["chargingDone"]

    def __init__(self):
        self.chargingDone = False

    def encode(self):
        buf = BytesIO()
        buf.write(L10ChargerComplete._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.chargingDone))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != L10ChargerComplete._get_packed_fingerprint():
            raise ValueError("Decode error")
        return L10ChargerComplete._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = L10ChargerComplete()
        self.chargingDone = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if L10ChargerComplete in parents: return 0
        tmphash = (0xc9d36eaa1a3bb634) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if L10ChargerComplete._packed_fingerprint is None:
            L10ChargerComplete._packed_fingerprint = struct.pack(">Q", L10ChargerComplete._get_hash_recursive([]))
        return L10ChargerComplete._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

