"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class L18PodState(object):
    __slots__ = ["state"]

    def __init__(self):
        self.state = ""

    def encode(self):
        buf = BytesIO()
        buf.write(L18PodState._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __state_encoded = self.state.encode('utf-8')
        buf.write(struct.pack('>I', len(__state_encoded)+1))
        buf.write(__state_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != L18PodState._get_packed_fingerprint():
            raise ValueError("Decode error")
        return L18PodState._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = L18PodState()
        __state_len = struct.unpack('>I', buf.read(4))[0]
        self.state = buf.read(__state_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if L18PodState in parents: return 0
        tmphash = (0x4c9c80a6adce9864) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if L18PodState._packed_fingerprint is None:
            L18PodState._packed_fingerprint = struct.pack(">Q", L18PodState._get_hash_recursive([]))
        return L18PodState._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

