"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class L19MagnetCommand(object):
    __slots__ = ["switch"]

    def __init__(self):
        self.switch = False

    def encode(self):
        buf = BytesIO()
        buf.write(L19MagnetCommand._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.switch))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != L19MagnetCommand._get_packed_fingerprint():
            raise ValueError("Decode error")
        return L19MagnetCommand._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = L19MagnetCommand()
        self.switch = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if L19MagnetCommand in parents: return 0
        tmphash = (0x90a9a1c096c7bbee) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if L19MagnetCommand._packed_fingerprint is None:
            L19MagnetCommand._packed_fingerprint = struct.pack(">Q", L19MagnetCommand._get_hash_recursive([]))
        return L19MagnetCommand._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

