"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class L20CompassHeading(object):
    __slots__ = ["direction"]

    def __init__(self):
        self.direction = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(L20CompassHeading._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">f", self.direction))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != L20CompassHeading._get_packed_fingerprint():
            raise ValueError("Decode error")
        return L20CompassHeading._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = L20CompassHeading()
        self.direction = struct.unpack(">f", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if L20CompassHeading in parents: return 0
        tmphash = (0xc927b47fd5e0d804) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if L20CompassHeading._packed_fingerprint is None:
            L20CompassHeading._packed_fingerprint = struct.pack(">Q", L20CompassHeading._get_hash_recursive([]))
        return L20CompassHeading._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

